### ISSUE TITLE
Phone starts with `pick up` transition.

### ISSUE THREAD

**Issue by urstruktur** [krachzack/fernspielapparat#10]
Starting fernspielapparat the 'pickup' state transition is executed without picking up the phone.

Tested with attached phonebook:
[test.txt](https://github.com/krachzack/fernspielapparat/files/3374334/test.txt)

**Comment by tapirbug** [comment]
The dial logic indeed assumes that the phone is hung up when starting up.

This means that any transition that occurs from the initial state when hanging up is only triggered when the phone was picked up in the meantime. When starting picked up, this immediately leads to a transition.

This is inconsistent, so I am re-opening this so initial transitions work both for hang up and for pick up.

**Comment by tapirbug** [comment]
Wait, I just realized you said pick up is executed when not picking up? I misunderstood, closing this and opening a new issue for the initial transitions.

Feel free to re-open if you are still experiencing the issue you described here.
