### ISSUE TITLE
Phone does not ring

### ISSUE THREAD

**Issue by urstruktur** [krachzack/fernspielapparat#9]
Phone does ring when testing it with `-t`, yet it does not ring when a state in a phonebook should ring the bell.

Tested with following phonebook:
[test.txt](https://github.com/krachzack/fernspielapparat/files/3374320/test.txt)

**Comment by tapirbug** [comment]
A bug caused actuators to not be activated when a new state was entered. This broke the bell, since it communicates with the phone on state activation.

7a1020f249e3c77a45bd72384cc94109a421db09 fixes the issue by activating on state transitions.
